"""empty message

Revision ID: dc1013cce36b
Revises: 
Create Date: 2021-04-12 01:12:13.932405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1013cce36b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zqsb')
    op.drop_table('zqsb_news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zqsb_news',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('master_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['zqsb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zqsb',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), nullable=True),
    sa.Column('publish_date', sa.DATETIME(), nullable=True),
    sa.Column('np', sa.INTEGER(), nullable=True),
    sa.Column('pdf_url', sa.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
